FROM nginx:1.27.3

COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN mkdir /etc/nginx/ssl

# Copie des fichiers statiques dans le répertoire attendu par Nginx


#EXPOSE 443
#
#CMD ["nginx", "-g", "daemon off;"]
