services:
  mariadb:
    init: true
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
      
  nginx:
    init: true
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    init: true
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  mariadb:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/terussar/data/mariadb"

  wordpress:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/terussar/data/wordpress"

networks:
  inception:
    name: inception
    driver: bridge
